---
name: Update Flake Lock

on:
  schedule:
    # daily at 04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch: null

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(deps): bump flake.lock"
          commit_user_name: Flake Bot
          commit_options: --no-verify --signoff
          commit_author: Flake Bot <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
